const template = require('../config/template.json');

const getMyStyle = ({ nameError }) => ({
	startPicture: {
		height: '18vh',
		minHeight: '150px',
		alignSelf: 'center',
		filter: 'drop-shadow(0 0 12px rgba(255,203,5,0.4))',
	},
	startInputContainer: {
		marginTop: '32px',
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'center',
		gap: '12px',
	},
	nameInput: {
		width: '180px',
		padding: '10px 14px',
		border: nameError ? '2px solid ' + template.colors.pokemonRed : '2px solid ' + template.colors.green,
		borderRadius: '6px',
		backgroundColor: template.colors.bgPanelLight,
		color: template.colors.white,
		fontFamily: template.fonts.pokemon,
		fontSize: template.sizes.defaultFont,
		outline: 'none',
		boxShadow: nameError ? '0 0 8px rgba(204,0,0,0.4)' : '0 0 8px rgba(0,204,102,0.3)',
	},
	startButton: {
		width: '160px',
		backgroundColor: template.colors.pokemonRed,
		color: template.colors.white,
		fontFamily: template.fonts.pokemon,
		fontSize: template.sizes.defaultFont,
		cursor: 'pointer',
		textTransform: 'uppercase',
		padding: '10px 0',
		border: '2px solid ' + template.colors.pokemonRedDark,
		borderRadius: '6px',
		boxShadow: '0 4px 0px ' + template.colors.pokemonRedDark + ', 0 6px 12px rgba(0,0,0,0.3)',
		letterSpacing: '2px',
	},
	scoreText: {
		fontFamily: template.fonts.pokemon,
		fontSize: template.sizes.dataFont,
		alignSelf: 'center',
		marginTop: '24px',
		color: template.colors.pokemonYellow,
		textShadow: '1px 1px 0px rgba(0,0,0,0.5)',
	},
	ladderLabel: {
		fontFamily: template.fonts.pokemon,
		fontSize: template.sizes.innerHeadlineFont,
		alignSelf: 'center',
		marginTop: '20px',
		color: template.colors.gold,
		textShadow: '1px 1px 0px rgba(0,0,0,0.5)',
		letterSpacing: '2px',
	},
	ladderList: {
		marginTop: template.sizes.smallMargin,
		alignSelf: 'center',
		listStyleType: 'none',
		backgroundColor: template.colors.bgPanelLight,
		paddingLeft: '24px',
		paddingRight: '24px',
		paddingTop: '12px',
		paddingBottom: '12px',
		minWidth: '60%',
		border: '2px solid ' + template.colors.borderLight,
		borderRadius: '8px',
		boxShadow: 'inset 0 0 15px rgba(0,0,0,0.3)',
	},
	ladderEntry: {
		fontFamily: template.fonts.pokemon,
		fontSize: template.sizes.defaultFont,
		marginBottom: '6px',
		width: '100%',
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'center',
		color: template.colors.textLight,
		padding: '4px 0',
	},
});

module.exports = {
	getMyStyle,
};
